// backend/server/services/codeGeneratorService.js
// Generates a complete, self-contained Node.js/Express backend application
// for a given project. This generated app is what gets containerised and deployed.
//
// The generated app:
//   - Connects to the SAME PostgreSQL database as the main Stackbase server
//   - Serves only the tables belonging to this project
//   - Has its own port and API key validation
//   - Is a standalone package.json + server.js bundle

const path = require('path');
const fs = require('fs');
const os = require('os');

/**
 * Generate project server code as a string.
 * This is the server.js that runs inside the deployed container.
 *
 * @param {Object} project - Project record from Prisma
 * @param {Array}  tables  - Array of ProjectTable records
 * @param {Array}  apiKeys - Array of ApiKey records (raw keys)
 * @returns {string} server.js source code
 */
const generateProjectServerCode = (project, tables, apiKeys) => {
  const tableRoutes = tables.map((t) => {
    const pg = t.pgTableName || `prj_${project.id.replace(/-/g,'').slice(0,8)}_${t.tableName}`;
    return `
  // Table: ${t.tableName}
  app.get('/api/${pg}', requireKey, async (req, res) => {
    try {
      const { limit = 20, offset = 0, order_by = 'created_at', order = 'desc', ...filters } = req.query;
      const safeLimit = Math.min(Math.max(parseInt(limit)||20,1),100);
      const safeOffset = Math.max(parseInt(offset)||0,0);
      const safeOrder = order.toLowerCase() === 'asc' ? 'ASC' : 'DESC';
      const filterKeys = Object.keys(filters);
      let where = ''; const params = [];
      if (filterKeys.length > 0) {
        const conds = filterKeys.map((k,i) => { params.push(filters[k]); return k + ' = $' + (i+1); });
        where = 'WHERE ' + conds.join(' AND ');
      }
      const countRes = await pool.query('SELECT COUNT(*) FROM ${pg} ' + where, params);
      const rows = await pool.query('SELECT * FROM ${pg} ' + where + ' ORDER BY ' + order_by + ' ' + safeOrder + ' LIMIT $' + (params.length+1) + ' OFFSET $' + (params.length+2), [...params, safeLimit, safeOffset]);
      res.json({ success: true, data: rows.rows, meta: { total: parseInt(countRes.rows[0].count), limit: safeLimit, offset: safeOffset } });
    } catch(e) { res.status(500).json({ success: false, error: e.message }); }
  });
  app.get('/api/${pg}/:id', requireKey, async (req, res) => {
    try {
      const r = await pool.query('SELECT * FROM ${pg} WHERE id = $1', [req.params.id]);
      if (!r.rows.length) return res.status(404).json({ success: false, error: 'Not found' });
      res.json({ success: true, data: r.rows[0] });
    } catch(e) { res.status(500).json({ success: false, error: e.message }); }
  });
  app.post('/api/${pg}', requireKey, async (req, res) => {
    try {
      const { id, created_at, updated_at, ...data } = req.body;
      const keys = Object.keys(data);
      if (!keys.length) return res.status(400).json({ success: false, error: 'Empty body' });
      const vals = keys.map(k => data[k]);
      const ph = vals.map((_,i) => '$'+(i+1)).join(', ');
      const r = await pool.query('INSERT INTO ${pg} (' + keys.join(', ') + ') VALUES (' + ph + ') RETURNING *', vals);
      res.status(201).json({ success: true, data: r.rows[0] });
    } catch(e) { res.status(500).json({ success: false, error: e.message }); }
  });
  app.put('/api/${pg}/:id', requireKey, async (req, res) => {
    try {
      const { id, created_at, updated_at, ...data } = req.body;
      const keys = Object.keys(data);
      if (!keys.length) return res.status(400).json({ success: false, error: 'Nothing to update' });
      const set = keys.map((k,i) => k + ' = $' + (i+1)).join(', ');
      const r = await pool.query('UPDATE ${pg} SET ' + set + ', updated_at = NOW() WHERE id = $' + (keys.length+1) + ' RETURNING *', [...keys.map(k=>data[k]), req.params.id]);
      if (!r.rows.length) return res.status(404).json({ success: false, error: 'Not found' });
      res.json({ success: true, data: r.rows[0] });
    } catch(e) { res.status(500).json({ success: false, error: e.message }); }
  });
  app.delete('/api/${pg}/:id', requireKey, async (req, res) => {
    try {
      const r = await pool.query('DELETE FROM ${pg} WHERE id = $1 RETURNING *', [req.params.id]);
      if (!r.rows.length) return res.status(404).json({ success: false, error: 'Not found' });
      res.json({ success: true, message: 'Deleted', data: r.rows[0] });
    } catch(e) { res.status(500).json({ success: false, error: e.message }); }
  });`;
  }).join('\n');

  const validKeys = apiKeys.map((k) => `"${k.key}"`).join(', ');

  return `// Auto-generated by Stackbase — Project: ${project.name}
// DO NOT EDIT MANUALLY

const express = require('express');
const { Pool } = require('pg');
const cors = require('cors');

const app = express();
const PORT = process.env.PORT || 8080;
const DATABASE_URL = process.env.DATABASE_URL;
const VALID_API_KEYS = [${validKeys}];

app.use(cors());
app.use(express.json({ limit: '10mb' }));

const pool = new Pool({ connectionString: DATABASE_URL });

const requireKey = (req, res, next) => {
  const key = req.headers['x-api-key'] || (req.headers.authorization || '').replace('Bearer ', '');
  if (!VALID_API_KEYS.includes(key)) {
    return res.status(401).json({ success: false, error: 'Invalid API key' });
  }
  next();
};

app.get('/health', (req, res) => {
  res.json({ status: 'ok', project: '${project.name}', timestamp: new Date().toISOString() });
});

${tableRoutes}

app.use((req, res) => res.status(404).json({ success: false, error: 'Not found' }));

pool.query('SELECT 1').then(() => {
  app.listen(PORT, '0.0.0.0', () => {
  console.log('[${project.name}] Server running on port', PORT);
 console.log('[${project.name}] Tables: ${tables.map((t)=>t.tableName).join(', ')}');
});
}).catch(err => {
  console.error('[${project.name}] DB connection failed:', err.message);
  process.exit(1);
});
`;
};

/**
 * Generate a package.json for the deployed project app.
 */
const generateProjectPackageJson = (project) => JSON.stringify({
  name: `stackbase-project-${project.id.slice(0, 8)}`,
  version: '1.0.0',
  main: 'server.js',
  scripts: { start: 'node server.js' },
  dependencies: { express: '^4.18.3', pg: '^8.11.3', cors: '^2.8.5' },
}, null, 2);

/**
 * Generate a Dockerfile for the project container.
 */
const generateDockerfile = () => `FROM node:18-alpine
WORKDIR /app
COPY package.json .
RUN npm install --production
COPY server.js .
EXPOSE 8080
CMD ["node", "server.js"]
`;

/**
 * Write generated project files to a temp directory.
 * Returns the temp dir path.
 *
 * @param {Object} project
 * @param {Array}  tables
 * @param {Array}  apiKeys
 * @returns {Promise<string>} temp directory path
 */
const writeProjectFilesToTemp = async (project, tables, apiKeys) => {
  const tmpDir = path.join(os.tmpdir(), `stackbase-prj-${project.id.slice(0, 8)}-${Date.now()}`);
  fs.mkdirSync(tmpDir, { recursive: true });

  fs.writeFileSync(path.join(tmpDir, 'server.js'), generateProjectServerCode(project, tables, apiKeys));
  fs.writeFileSync(path.join(tmpDir, 'package.json'), generateProjectPackageJson(project));
  fs.writeFileSync(path.join(tmpDir, 'Dockerfile'), generateDockerfile());

  return tmpDir;
};

module.exports = {
  generateProjectServerCode,
  generateProjectPackageJson,
  generateDockerfile,
  writeProjectFilesToTemp,
};
